# Generated by Django 3.0.4 on 2020-03-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('mode', models.IntegerField(choices=[(0, 'normal'), (1, 'stackable'), (2, 'repeatable')])),
                ('feat_type', models.IntegerField(choices=[(0, 'general'), (1, 'metamagic'), (2, 'special'), (3, 'object-creation')])),
                ('benefit', models.CharField(max_length=500)),
                ('parent_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
