# Generated by Django 3.0.4 on 2020-03-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_modeling', '0002_feat_prerequisite_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='feat',
            name='prerequisites',
            field=models.ManyToManyField(related_name='required_by', to='feat_modeling.Feat'),
        ),
    ]
