# Generated by Django 3.0.4 on 2020-03-11 01:34

from django.db import migrations


def migrate_forwards(apps, schema):
    Skill = apps.get_model('feat_modeling', 'Skill')
    Attribute = apps.get_model('feat_modeling', 'Attribute')

    for feat in Feat.objects.all():
        prerequisites = json.loads(feat.prerequisite_names)
        feats = (
            Feat.objects.filter(name__in=prerequisites)
            | Feat.objects.filter(name=feat.parent_name)
        )
        if feats.exists():
            feat.prerequisites.set(feats)
            feat.save()



class Migration(migrations.Migration):

    dependencies = [
        ('feat_modeling', '0005_attribute'),
    ]

    operations = [
    ]
