# Generated by Django 3.0.4 on 2020-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_modeling', '0006_auto_20200311_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='armor_penalty',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'normal'), (2, 'weight')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='governing_attr',
            field=models.CharField(choices=[('str', 'str'), ('dex', 'dex'), ('con', 'con'), ('int', 'int'), ('wis', 'wis'), ('cha', 'cha')], default=None, max_length=3),
            preserve_default=False,
        ),
    ]
