# Generated by Django 3.0.4 on 2020-03-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_modeling', '0007_auto_20200311_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='trained_only',
            field=models.BooleanField(default=True),
        ),
    ]
