# Generated by Django 3.0.4 on 2020-03-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feat_modeling', '0008_auto_20200311_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feat',
            name='benefit',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='NumericalFeatRequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_item_id', models.IntegerField()),
                ('required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='NumericalFeatEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.IntegerField()),
                ('modify_item_id', models.IntegerField()),
                ('modify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='feat',
            name='effects',
            field=models.ManyToManyField(to='feat_modeling.NumericalFeatEffect'),
        ),
        migrations.AddField(
            model_name='feat',
            name='requisites',
            field=models.ManyToManyField(to='feat_modeling.NumericalFeatRequisite'),
        ),
    ]
