# Generated by Django 3.0.4 on 2020-03-11 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feat_modeling', '0009_auto_20200311_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feat',
            name='effects',
        ),
        migrations.RemoveField(
            model_name='feat',
            name='requisites',
        ),
        migrations.AddField(
            model_name='numericalfeateffect',
            name='feat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='feat_modeling.Feat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numericalfeatrequisite',
            name='feat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='feat_modeling.Feat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feat',
            name='parent_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='feat',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='feat_modeling.Feat'),
        ),
    ]
