# Generated by Django 3.0.4 on 2020-03-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feat_modeling', '0010_auto_20200311_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numericalfeateffect',
            name='modify',
        ),
        migrations.AddField(
            model_name='numericalfeateffect',
            name='modify',
            field=models.ManyToManyField(to='contenttypes.ContentType'),
        ),
    ]
