# Generated by Django 3.0.4 on 2020-03-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feat_modeling', '0011_auto_20200312_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('character_level', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('attack_class', models.IntegerField(choices=[(1, 'poor'), (2, 'normal'), (3, 'great')])),
            ],
        ),
        migrations.RemoveField(
            model_name='numericalfeateffect',
            name='modify',
        ),
        migrations.AddField(
            model_name='numericalfeateffect',
            name='modify',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SkillContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranks', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='feat_modeling.Character')),
                ('skill_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feat_modeling.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feat_modeling.CharacterClass'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_set',
            field=models.ManyToManyField(through='feat_modeling.SkillContainer', to='feat_modeling.Skill'),
        ),
    ]
