# Generated by Django 3.0.4 on 2020-03-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_modeling', '0012_auto_20200315_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillcontainer',
            name='ranks',
            field=models.IntegerField(default=0),
        ),
    ]
