# Generated by Django 3.0.4 on 2020-03-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_modeling', '0013_auto_20200315_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.ManyToManyField(to='feat_modeling.Feat'),
        ),
    ]
